# Generated by Django 2.2.6 on 2019-10-05 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('texto', models.TextField()),
                ('prazo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=12)),
                ('rg', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Justica.Departamento')),
                ('interessados', models.ManyToManyField(related_name='Interessados', to='App_Justica.Pessoa')),
                ('investigados', models.ManyToManyField(related_name='Investigados', to='App_Justica.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App_Justica.Pessoa')),
                ('cargo', models.CharField(max_length=20)),
                ('matricula', models.IntegerField()),
            ],
            bases=('App_Justica.pessoa',),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App_Justica.Documento')),
                ('justificativa', models.TextField()),
                ('maisPra', models.DateField()),
            ],
            bases=('App_Justica.documento',),
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Destino', to='App_Justica.Departamento')),
                ('origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Origem', to='App_Justica.Departamento')),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Justica.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='processo',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Justica.Funcionario'),
        ),
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App_Justica.Documento')),
                ('proce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Justica.Processo')),
            ],
            bases=('App_Justica.documento',),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App_Justica.Documento')),
                ('dataenvio', models.DateField()),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Justica.Departamento')),
            ],
            bases=('App_Justica.documento',),
        ),
    ]
